### ISSUE TITLE
AMQ Broker channel 7.x might be incompatible with mqttv3 v1.2.2 jar

### ISSUE THREAD

**Issue by mhjacks** [hybrid-cloud-patterns/industrial-edge#96]
This causes the machine-sensor pods to not function correctly.

Recently the 7.x AMQ broker channel moved to v7.9 of the AMQ broker - we were expecting 7.8.

Plan of attack is to specify v7.8 in the subscription spec (7.8 is a long term support release of AMQ), and rebuild the cluster, seeing if that allows the machine sensor pods to come up.

Error logs from the machine sensor pods:
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
52
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/iot-software-sensor-0.0.1-SNAPSHOT.jar
51
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
50
49
  .   ____          _            __ _ _2022-04-19T20:34:02.728374348Z
48
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \2022-04-19T20:34:02.728442581Z
47
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \2022-04-19T20:34:02.728501767Z
46
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )2022-04-19T20:34:02.728566219Z
45
  '  |____| .__|_| |_|_| |_\__, | / / / /2022-04-19T20:34:02.728953111Z
44
 =========|_|==============|___/=/_/_/_/2022-04-19T20:34:02.729039178Z
43
 :: Spring Boot ::        (v2.2.1.RELEASE)2022-04-19T20:34:02.733999368Z
42
41
I> No access restrictor found, access to any MBean is allowed2022-04-19T20:34:02.832289331Z
40
Jolokia: Agent started with URL https://10.131.0.66:8778/jolokia/
39
2022-04-19 20:34:02.888  INFO 1 --- [           main] com.redhat.examples.iot.Application      : Starting Application v0.0.1-SNAPSHOT on machine-sensor-1-568464bfdc-tz6jv with PID 1 (/deployments/iot-software-sensor-0.0.1-SNAPSHOT.jar started by jboss in /deployments)
38
2022-04-19 20:34:02.891  INFO 1 --- [           main] com.redhat.examples.iot.Application      : No active profile set, falling back to default profiles: default
37
2022-04-19 20:34:05.282  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
36
2022-04-19 20:34:05.447  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
35
2022-04-19 20:34:05.448  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.27]
34
2022-04-19 20:34:05.511  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
33
2022-04-19 20:34:05.511  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2568 ms
32
2022-04-19 20:34:06.303  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : Starting up...
31
2022-04-19 20:34:06.303  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : ---------------------------
30
2022-04-19 20:34:06.303  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : Application Name: iot-sensor
29
2022-04-19 20:34:06.305  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : Device ID: pump-1
28
2022-04-19 20:34:06.305  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : ---------------------------
27
2022-04-19 20:34:06.310  INFO 1 --- [           main] c.redhat.examples.iot.SchedulerManager   : Sensor type temperature disabled
26
2022-04-19 20:34:06.356  INFO 1 --- [           main] c.redhat.examples.iot.mqtt.MqttProducer  : MQTT Connect options
25
2022-04-19 20:34:06.358  INFO 1 --- [           main] c.redhat.examples.iot.mqtt.MqttProducer  :
24
============== Connection options ==============
23
CleanSession                :  true
22
SocketFactory               :  null
21
MqttVersion                 :  0
20
KeepAliveInterval           :  60
19
ConTimeout                  :  30
18
UserName                    :  iotuser
17
SSLProperties               :  null
16
WillDestination             :  null
15
==========================================
14
13
2022-04-19 20:34:06.389 ERROR 1 --- [           main] c.redhat.examples.iot.mqtt.MqttProducer  : MqttException
12
11
org.eclipse.paho.client.mqttv3.MqttException: MqttException
10
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
9
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:736) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
8
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_322]
7
Caused by: java.io.IOException: WebSocket Response header: Incorrect connection header
6
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:157) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
5
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
4
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule.start(WebSocketNetworkModule.java:67) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
3
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722) ~[org.eclipse.paho.client.mqttv3-1.2.2.jar!/:na]
2
	... 1 common frames omitted
1
```

**Comment by mhjacks** [comment]
Got this on a new 4.9 install using the 7.8 channel:
```api-server resource not found installing CustomResourceDefinition activemqartemises.broker.amq.io: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.```

**Comment by mhjacks** [comment]
On new cluster builds for both OCP 4.8 and 4.9 I could not reproduce this. Closing for now as this seems to be some odd edge case but seemingly not a software incompatibility.
